title: Temjana Angjusheva
description: This is my personal portfolio, intended to showcase my best work in digital design.
social_media_share_image: /images/temjana-picture.png
disqus-identifier:
google-analytics: