[component]
structures = [ "content_blocks" ]
label = "Contact Form"
description = "Generic contact form"
icon = "wysiwyg"
tags = ["Text"]

[props]
form_title = "Let's work together!"
form_description = "Maybe you want me on your team. You might want to ask me a question, or simply you just want to chat. Whatever it might be, I'd love to talk! Shoot me a message below."
form_success_page = "/"
form_submission_email = "temi.angjusheva@gmail.com" # Add your email for contact form
form_button_text = "Send now"